export const ROUTES = {
  AUTH: {
    BASE: '/api/auth',
    LOGIN: '/login',
    REGISTER: '/register',
    REFRESH: '/refresh',
    LOGOUT: '/logout',
    GOOGLE: '/google',
    FORGOT_PASSWORD: '/forgot-password',
    RESET_PASSWORD: '/reset-password/:email',
    VERIFY_EMAIL: '/verify-email/:id',
    RESEND_EMAIL: '/resend-email',
  },
  USER: {
    BASE: '/api/user',
    PROFILE: '/profile',
    UPDATE: '/:id',
    DELETE: '/:id',
    GET_ONE: '/:id',
    GET_ALL: '/',
    DISCONNECT_DEVICE: '/disconnect-device/:id',
    DISCONNECT_ALL_DEVICES: '/disconnect-all-devices',
    GET_DEVICES: '/devices',
    CREATE_ENCRYPTION_KEY: '/encryption-key',
    RESET_ENCRYPTION_KEY: '/reset-encryption-key',
    CHANGE_ENCRYPTION_KEY: '/change-encryption-key',
    CHANGE_PASSWORD: '/change-password',
  },
  CARD: {
    BASE: '/api/card',
    CREATE: '/',
    GET_ALL: '/',
    GET_ONE: '/:id',
    UPDATE: '/:id',
    DELETE: '/:id',
  },
  SUPPLIER: {
    BASE: '/api/supplier',
    CREATE: '/',
    GET_ALL: '/',
    GET_ONE: '/:id',
    UPDATE: '/:id',
    DELETE: '/:id',
  },
  SETTINGS: {
    BASE: '/api/settings',
    CREATE: '/',
    GET_ALL: '/',
    GET_ONE: '/:id',
    UPDATE: '/:id',
    DELETE: '/:id',
  },
};
