name: Scheduled HTTP Requests

on:
  schedule:
  - cron: '0 0 * * *' # Once a day at midnight UTC
  - cron: '*/5 * * * *' # Every 5 minutes

jobs:
  daily-requests:
    if: github.event.schedule == '0 0 * * *'
    runs-on: ubuntu-latest
    steps:
    - name: Scrape gift card suppliers once a day
      run: |
        curl -s https://gift-cards-api.vercel.app/api/supplier/scrape/buyme
        curl -s https://gift-cards-api.vercel.app/api/supplier/scrape/lovecard
        curl -s https://gift-cards-api.vercel.app/api/supplier/scrape/maxgiftcard
        curl -s https://gift-cards-api.vercel.app/api/supplier/scrape/goldcard
        curl -s https://gift-cards-api.vercel.app/api/supplier/scrape/nofshonit
        curl -s https://gift-cards-api.vercel.app/api/supplier/scrape/dreamcard

  frequent-request:
    if: github.event.schedule == '*/5 * * * *'
    runs-on: ubuntu-latest
    steps:
    - name: Check card expiry every 5 minutes
      run: curl -s https://gift-cards-api.vercel.app/api/card/email/month
